# Generated by Django 4.2.2 on 2023-06-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_logmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='phuong', max_length=300),
            preserve_default=False,
        ),
    ]
